const values = {
  '2009': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2010': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2011': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2012': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2013': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2014': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2015': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2016': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2017': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2018': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
  '2019': {
    income: 0,
    contributions_1: 0,
    contributions_2: 0,
    contributions_3: 0,
    contributions_4: 0,
    contributions_total: 0,
  },
}
